#
# This code is to be used exclusively in connection with ForgeRock\u2019s software or services.
# ForgeRock only offers ForgeRock software or services to legal entities who have entered
# into a binding license agreement with ForgeRock.
#


nodeDescription=REST API Call
nodeHelp=Extend the functionality of your Journey by invoking any third party service

restURL=Rest URL
restURL.help=URL of REST endpoint. Can include sharedState values using {{variable}} substitution.
requestMode=Request Type
requestMode.help=Type of request.
payload=Payload
payload.help=Payload/body to send with request. Can include sharedState values using {{variable}} substitution.
bodyType=Body Type
bodyType.help=Select body type to add appropriate "content-type" header.
queryParamsMap=Query Parameters
queryParamsMap.help=Set of key/value pairs containing request headers. Can include sharedState values using {{variable}} substitution.
headersMap=Headers
headersMap.help=Set of key/value pairs containing request headers. Can include sharedState values using {{variable}} substitution.
usemTLS=Use mTLS
usemTLS.help=If true will send client certificate with request.
publicCert=Public Certificate
publicCert.help=Public certificate in PEM format.
privateKey=Private Key
privateKey.help=Private key for certificate.
disableCertChecks=Disable Certificate Checks
disableCertChecks.help=If enabled then certificate path and hostname verifications are disabled. Recommended only for testing.
responseCodes=Response Codes
responseCodes.help=A list of response codes to map to specific outcomes. Use explicit codes such as 200, 401, etc, or wildcards such as 2** to match ranges.
statusCodeReturn=Status Code SharedState Variable
statusCodeReturn.help=Name of sharedState variable to store the request response status code.
bodyReturn=Returned Body SharedState Variable
bodyReturn.help=Name of sharedState variable to store the request response body.
timeout=Timeout (seconds)
timeout.help=Connection timeout in seconds

#Outcomes
NoMatchOutcome=No Response Match
ErrorOutcome=Error